# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{myrurema}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yutaka HARA"]
  s.date = %q{2010-09-01}
  s.default_executable = %q{rurema}
  s.description = %q{A tool for Rurema (the new Japanese Ruby reference manual)}
  s.email = %q{yutaka.hara/at/gmail.com}
  s.executables = ["rurema"]
  s.extra_rdoc_files = [
    "README.mkd"
  ]
  s.files = [
    "HISTORY",
     "README.mkd",
     "Rakefile",
     "VERSION",
     "bin/rurema",
     "features/basic_commands.feature",
     "main.rb",
     "spec/commands.rb",
     "src/myrurema.rb"
  ]
  s.homepage = %q{http://github.com/yhara/myrurema}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A tool for Rurema (the new Japanese Ruby reference manual)}
  s.test_files = [
    "spec/commands.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

